/**
 * useProductVariants Hook - Clean Architecture Implementation
 * Uses ProductService for business logic
 * Follows: UI → Logic (Services) → Data (API Services)
 */

import { useState } from 'react';
import { useToast } from '@/hooks/use-toast';
import { productsService } from '@/services/api/products.service';

interface ProductVariantForm {
  sku: string;
  price: string;
  discounted_price: string;
  stock_quantity: string;
  weight_kg: string;
  image_urls: string[];
}

interface UseProductVariantsReturn {
  variants: ProductVariantForm[];
  addVariant: () => void;
  removeVariant: (index: number) => void;
  updateVariant: (index: number, field: string, value: string) => void;
  addImageUrl: (variantIndex: number) => void;
  removeImageUrl: (variantIndex: number, imageIndex: number) => void;
  updateImageUrl: (variantIndex: number, imageIndex: number, value: string) => void;
  resetVariants: () => void;
  createAllVariants: (productId: number) => Promise<void>;
  createVariant: (productId: number, variantData: any) => Promise<void>;
  editVariant: (productId: number, variantId: number, data: any) => Promise<void>;
  deleteVariant: (productId: number, variantId: number) => Promise<void>;
}

const initialVariant: ProductVariantForm = {
  sku: '',
  price: '',
  discounted_price: '',
  stock_quantity: '',
  weight_kg: '',
  image_urls: [''],
};

export const useProductVariants = (): UseProductVariantsReturn => {
  const { toast } = useToast();
  const [variants, setVariants] = useState<ProductVariantForm[]>([{ ...initialVariant }]);

  const addVariant = () => {
    setVariants([...variants, { ...initialVariant }]);
  };

  const removeVariant = (index: number) => {
    if (variants.length > 1) {
      setVariants(variants.filter((_, i) => i !== index));
    }
  };

  const updateVariant = (index: number, field: string, value: string) => {
    const updated = [...variants];
    updated[index] = { ...updated[index], [field]: value };
    setVariants(updated);
  };

  const addImageUrl = (variantIndex: number) => {
    const updated = [...variants];
    updated[variantIndex].image_urls.push('');
    setVariants(updated);
  };

  const removeImageUrl = (variantIndex: number, imageIndex: number) => {
    const updated = [...variants];
    updated[variantIndex].image_urls.splice(imageIndex, 1);
    if (updated[variantIndex].image_urls.length === 0) {
      updated[variantIndex].image_urls = [''];
    }
    setVariants(updated);
  };

  const updateImageUrl = (variantIndex: number, imageIndex: number, value: string) => {
    const updated = [...variants];
    updated[variantIndex].image_urls[imageIndex] = value;
    setVariants(updated);
  };

  const resetVariants = () => {
    setVariants([{ ...initialVariant }]);
  };

  const createAllVariants = async (productId: number): Promise<void> => {
    // Validate all variants
    for (const variant of variants) {
      if (!variant.price || !variant.stock_quantity) {
        toast({
          title: 'Validation Error',
          description: 'All variants must have price and stock quantity',
          variant: 'destructive',
        });
        throw new Error('Validation failed');
      }
    }

    try {
      // Create all variants with images
      for (const variant of variants) {
        // Filter out empty image URLs
        const imageUrls = variant.image_urls.filter(url => url && url.trim() !== '');
        
        // Create variant (SKU will be auto-generated by backend)
        const variantResponse = await productsService.createVariant(productId, {
          price: parseFloat(variant.price),
          discounted_price: variant.discounted_price ? parseFloat(variant.discounted_price) : undefined,
          stock_quantity: parseInt(variant.stock_quantity),
          weight_kg: variant.weight_kg ? parseFloat(variant.weight_kg) : undefined,
          image_urls: imageUrls.length > 0 ? imageUrls : undefined,
        });

        // @ts-ignore - API response structure
        const variantId = variantResponse?.data?.id || variantResponse?.id;
      }

      toast({
        title: 'Success',
        description: 'All variants created successfully',
      });
      resetVariants();
    } catch (error: any) {
      const errorMessage = error?.errors?.[0] || error?.message || 'Failed to create variants';
      toast({
        title: 'Error',
        description: errorMessage,
        variant: 'destructive',
      });
      throw error;
    }
  };

  const createVariant = async (productId: number, variantData: {
    price: number;
    discounted_price?: number;
    stock_quantity: number;
    weight_kg?: number;
    image_urls?: string[];
    attribute_value_ids?: number[];
  }): Promise<void> => {
    try {
      await productsService.createVariant(productId, variantData);
      toast({
        title: 'Success',
        description: 'Variant created successfully',
      });
    } catch (error: any) {
      const errorMessage = error?.errors?.[0] || error?.message || 'Failed to create variant';
      toast({
        title: 'Error',
        description: errorMessage,
        variant: 'destructive',
      });
      throw error;
    }
  };

  const editVariant = async (productId: number, variantId: number, data: {
    price: number;
    discounted_price?: number;
    stock_quantity: number;
    weight_kg?: number;
    image_urls?: string[];
  }): Promise<void> => {
    try {
      await productsService.updateVariant(productId, variantId, data);
      toast({
        title: 'Success',
        description: 'Variant updated successfully',
      });
    } catch (error: any) {
      const errorMessage = error?.errors?.[0] || error?.message || 'Failed to update variant';
      toast({
        title: 'Error',
        description: errorMessage,
        variant: 'destructive',
      });
      throw error;
    }
  };

  const deleteVariant = async (productId: number, variantId: number): Promise<void> => {
    try {
      await productsService.deleteVariant(productId, variantId);
      toast({
        title: 'Success',
        description: 'Variant deleted successfully',
      });
    } catch (error: any) {
      const errorMessage = error?.errors?.[0] || error?.message || 'Failed to delete variant';
      toast({
        title: 'Error',
        description: errorMessage,
        variant: 'destructive',
      });
      throw error;
    }
  };

  return {
    variants,
    addVariant,
    removeVariant,
    updateVariant,
    addImageUrl,
    removeImageUrl,
    updateImageUrl,
    resetVariants,
    createAllVariants,
    createVariant,
    editVariant,
    deleteVariant,
  };
};

